Model GAP_hcp_bcc_varceel16_r2, Test burgers_path
Test run at 2018-10-30 19:22

model file: ../../../models/Ti/GAP_hcp_bcc_varceel16_r2/model.py
============================================================
Traceback (most recent call last):
  File "run-model-test-cas.py", line 82, in <module>
    sys.stdout.write(open(model_file).read())
IOError: [Errno 2] No such file or directory: '../../../models/Ti/GAP_hcp_bcc_varceel16_r2/model.py'
