Model SW, Test surface-energy-100-unrelaxed
Test run at 2018-09-06 20:20

model file: ../../../models/Ti/SW/model.py
============================================================
Traceback (most recent call last):
  File "run-model-test-cas.py", line 79, in <module>
    sys.stdout.write(open(model_file).read())
IOError: [Errno 2] No such file or directory: '../../../models/Ti/SW/model.py'
