Model GAP, Test phonon
Test run at 2018-10-05 18:00

model file: ../../../models/Ti/GAP/model.py
============================================================
Traceback (most recent call last):
  File "run-model-test-cas.py", line 82, in <module>
    sys.stdout.write(open(model_file).read())
IOError: [Errno 2] No such file or directory: '../../../models/Ti/GAP/model.py'
