Model GAP_hcp_bcc_co, Test phonon_hcp
Test run at 2018-10-11 22:15

model file: ../../../models/Ti/GAP_hcp_bcc_co/model.py
============================================================
Traceback (most recent call last):
  File "run-model-test-cas.py", line 82, in <module>
    sys.stdout.write(open(model_file).read())
IOError: [Errno 2] No such file or directory: '../../../models/Ti/GAP_hcp_bcc_co/model.py'
