Model GAP_vc16_sp, Test bulk_bcc
Test run at 2018-11-05 16:53

model file: ../../../models/Ti/GAP_vc16_sp/model.py
============================================================
Traceback (most recent call last):
  File "run-model-test-cas.py", line 82, in <module>
    sys.stdout.write(open(model_file).read())
IOError: [Errno 2] No such file or directory: '../../../models/Ti/GAP_vc16_sp/model.py'
