Model PIP_4BBL_uhr, Test dimer
Test run at 2018-11-13 19:39

model file: ../../../models/W/PIP_4BBL_uhr/model.py
============================================================
Traceback (most recent call last):
  File "run-model-test-cas.py", line 82, in <module>
    sys.stdout.write(open(model_file).read())
IOError: [Errno 2] No such file or directory: '../../../models/W/PIP_4BBL_uhr/model.py'
