Model GAP_6, Test bulk_bcc
Test run at 2018-09-06 12:05

model file: ../../../models/Si/GAP_6/model.py
============================================================
Traceback (most recent call last):
  File "run-model-test-cas.py", line 79, in <module>
    sys.stdout.write(open(model_file).read())
IOError: [Errno 2] No such file or directory: '../../../models/Si/GAP_6/model.py'
