Model GAP_2b_3b, Test force-constant-diamond
Test run at 2018-09-05 19:28

model file: ../../../models/Si/GAP_2b_3b/model.py
============================================================
Traceback (most recent call last):
  File "run-model-test.py", line 79, in <module>
    sys.stdout.write(open(model_file).read())
IOError: [Errno 2] No such file or directory: '../../../models/Si/GAP_2b_3b/model.py'
